version: "3.9"
services:

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    volumes:
      - ollama_volume:/root/.ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - llm_network
  
  chatbot:
    build: ./chatbot
    ports:
      - "8501:8501"

    restart: unless-stopped
    networks:
      - llm_network
    command:  ["streamlit", "run", "ollama_bot.py"]

volumes:
  ollama_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/kdlocpanda/personal/my_repos/josh_bot/data/ollama

networks:
  llm_network:
    driver: bridge